# Site wide configuration

title: Cascadian Music
locale: en_US
description: Providing affordable arrangements and compositions for marching, pep, and concert band!
logo: site-logo.png
search: true
url: http://cascadianmusic.github.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Cascadian Music
  avatar: bio-photo.jpg
  email: contact@cascadianmusic.net
  disqus-shortname:
  twitter: CascadianMusic
  facebook: CascadianMusic
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: CascadianMusic
  flickr: #username
  tumblr: CascadianMusic
  pinterest: CascadianMusic
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:

defaults:
  -
    scope:
      path: ""
    values:
      heading: false


